// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIgnore(arg1, arg2) {
  return window['go']['main']['App']['AddIgnore'](arg1, arg2);
}

export function AppIDs() {
  return window['go']['main']['App']['AppIDs']();
}

export function ChromeSafeMode() {
  return window['go']['main']['App']['ChromeSafeMode']();
}

export function ChromeWholeUserData() {
  return window['go']['main']['App']['ChromeWholeUserData']();
}

export function DeleteBundle(arg1) {
  return window['go']['main']['App']['DeleteBundle'](arg1);
}

export function Diagnose() {
  return window['go']['main']['App']['Diagnose']();
}

export function Fetch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Fetch'](arg1, arg2, arg3, arg4);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function KeyInit() {
  return window['go']['main']['App']['KeyInit']();
}

export function KeyStatus() {
  return window['go']['main']['App']['KeyStatus']();
}

export function Matrix() {
  return window['go']['main']['App']['Matrix']();
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function Push(arg1, arg2) {
  return window['go']['main']['App']['Push'](arg1, arg2);
}

export function RemoveIgnore(arg1, arg2) {
  return window['go']['main']['App']['RemoveIgnore'](arg1, arg2);
}

export function RepairChrome() {
  return window['go']['main']['App']['RepairChrome']();
}

export function Restore(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Restore'](arg1, arg2, arg3, arg4);
}

export function SetChromeSafeMode(arg1) {
  return window['go']['main']['App']['SetChromeSafeMode'](arg1);
}

export function SetChromeWholeUserData(arg1) {
  return window['go']['main']['App']['SetChromeWholeUserData'](arg1);
}

export function SetTailscalePath(arg1) {
  return window['go']['main']['App']['SetTailscalePath'](arg1);
}

export function Snapshot(arg1) {
  return window['go']['main']['App']['Snapshot'](arg1);
}

export function SpoolDir() {
  return window['go']['main']['App']['SpoolDir']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
