// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restore} from '../models';
import {settings} from '../models';
import {main} from '../models';
import {service} from '../models';

export function AddIgnore(arg1:string,arg2:string):Promise<void>;

export function AppIDs():Promise<Array<string>>;

export function ChromeSafeMode():Promise<boolean>;

export function ChromeWholeUserData():Promise<boolean>;

export function DeleteBundle(arg1:string):Promise<void>;

export function Diagnose():Promise<string>;

export function Fetch(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<Array<restore.AppOutcome>>;

export function GetSettings():Promise<settings.Settings>;

export function KeyInit():Promise<string>;

export function KeyStatus():Promise<main.KeyStatus>;

export function Matrix():Promise<service.Matrix>;

export function Overview():Promise<service.Overview>;

export function Push(arg1:string,arg2:string):Promise<void>;

export function RemoveIgnore(arg1:string,arg2:string):Promise<void>;

export function Restore(arg1:string,arg2:Array<string>,arg3:boolean,arg4:boolean):Promise<Array<restore.AppOutcome>>;

export function SetChromeSafeMode(arg1:boolean):Promise<void>;

export function SetChromeWholeUserData(arg1:boolean):Promise<void>;

export function SetTailscalePath(arg1:string):Promise<void>;

export function Snapshot(arg1:Array<string>):Promise<main.SnapshotResult>;

export function SpoolDir():Promise<string>;

export function Version():Promise<string>;
